### ISSUE TITLE
Error with moment-timezone function

### ISSUE THREAD

**Issue by satyashani** [StrideSpark/snowflake-sdk#1]
.../snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/sf_timestamp.js:71
    moment = moment.tz(timezone);
                    ^

TypeError: moment.tz is not a function
    at new SfTimestamp (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/sf_timestamp.js:71:21)
    at convertRawTimestampHelper (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/column.js:481:10)
    at Object.convertRawTimestampLtz [as convert] (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/column.js:346:10)
    at Column.extractFromRow (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/column.js:730:21)
    at Column.getRowValue (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/column.js:205:27)
    at Object.getColumnValue (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/chunk.js:348:28)
    at externalizeRow (/var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/row_stream.js:391:59)
    at /var/www/xray/snowflakeadmin/node_modules/snowflake-sdk/lib/connection/result/row_stream.js:168:17
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by satyashani** [comment]
This problem disappeared when I installed latest version of moment-timezone (0.5.13) and updated the package.json in snowflake-sdk
